(()=>{
'use strict';
const cv=document.getElementById('game'),ctx=cv.getContext('2d');
const scoreEl=document.getElementById('score'),streakEl=document.getElementById('streak'),timeEl=document.getElementById('time'),hitEl=document.getElementById('hitName'),energyBar=document.getElementById('energyBar'),overlay=document.getElementById('overlay');
let W=0,H=0,DPR=1,last=0,running=false,spawnT=0,ringT=0,hazardT=0,bonusT=0,timeLeft=75,score=0,streak=0,bestStreak=0,shake=0,flash=0,audio=null;
const keys=new Set(),objects=[],rings=[],stars=[],bursts=[],darts=[];
const mouse={active:false,x:0,y:0};
const player={x:160,y:220,vx:0,vy:0,r:28,energy:100,dash:0,inv:0,slow:0,fire:0};
const TYPES={
 candy:{name:'moon candy',r:12,speed:210,score:10,energy:4,color:'#f9ff00',kind:'good'},
 star:{name:'star fruit',r:15,speed:235,score:24,energy:2,color:'#00f5ff',kind:'good'},
 bubble:{name:'dream bubble',r:18,speed:165,score:12,energy:18,color:'#24fff2',kind:'good'},
 clock:{name:'time charm',r:16,speed:190,score:8,time:7,color:'#8cff00',kind:'good'},
 feather:{name:'dash feather',r:14,speed:245,score:16,energy:9,color:'#ff3df2',kind:'good'},
 bolt:{name:'storm bolt',r:18,speed:280,damage:13,color:'#fffb00',kind:'bad'},
 pillow:{name:'sleepy pillow',r:20,speed:175,damage:8,slow:1.3,color:'#b96cff',kind:'bad'},
 cloud:{name:'ghost cloud',r:34,speed:155,damage:18,color:'#ff75d8',kind:'bad'}
};
const rand=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>v<a?a:v>b?b:v,pick=a=>a[(Math.random()*a.length)|0];
function resize(){DPR=Math.min(2,window.devicePixelRatio||1);W=innerWidth;H=innerHeight;cv.width=Math.floor(W*DPR);cv.height=Math.floor(H*DPR);ctx.setTransform(DPR,0,0,DPR,0,0);if(!stars.length){for(let i=0;i<110;i++)stars.push({x:rand(0,W),y:rand(0,H),r:rand(.5,2),s:rand(8,36),a:rand(.15,.72)})}}
function reset(){objects.length=0;rings.length=0;bursts.length=0;darts.length=0;score=0;streak=0;bestStreak=0;timeLeft=75;spawnT=0;ringT=1;hazardT=1.4;bonusT=2.2;shake=0;flash=0;hitEl.textContent='ready';player.x=Math.max(110,W*.16);player.y=H*.48;player.vx=0;player.vy=0;player.energy=100;player.dash=0;player.inv=0;player.slow=0;player.fire=0;mouse.active=false;running=true;overlay.classList.add('hidden');updateHud()}
function updateHud(){scoreEl.textContent=score;streakEl.textContent=streak;timeEl.textContent=Math.max(0,Math.ceil(timeLeft));energyBar.style.width=clamp(player.energy,0,100)+'%'}
function spawnObject(type){const d=TYPES[type];objects.push({type,x:W+rand(30,95),y:rand(78,H-84),r:d.r,t:0,vx:d.speed*rand(.9,1.18),bob:rand(0,Math.PI*2)})}
function spawnRing(){rings.push({x:W+70,y:rand(110,H-120),r:38,w:8,hit:false,t:0})}
function burst(x,y,color,n=14){for(let i=0;i<n;i++){const a=rand(0,Math.PI*2),sp=rand(60,230);bursts.push({x,y,vx:Math.cos(a)*sp,vy:Math.sin(a)*sp,life:1,color,r:rand(2,5)})}}
function trail(x,y,color,n=2){for(let i=0;i<n;i++)bursts.push({x:x+rand(-7,7),y:y+rand(-7,7),vx:rand(-42,42),vy:rand(-42,42),life:rand(.25,.55),color,r:rand(1.4,3.6)})}
function initAudio(){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;if(!audio)audio=new AC();if(audio.state==='suspended')audio.resume()}
function tone(freq,dur=.08,type='sine',gain=.055,sweep=1){if(!audio)return;const t=audio.currentTime,o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);if(sweep!==1)o.frequency.exponentialRampToValueAtTime(Math.max(30,freq*sweep),t+dur);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(gain,t+.012);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+dur+.03)}
function playShoot(){tone(740,.07,'triangle',.045,1.7);tone(1240,.08,'sine',.032,1.25)}
function playCollect(){tone(520,.06,'sine',.035,1.45);setTimeout(()=>tone(780,.08,'triangle',.034,1.18),45)}
function playRing(){tone(420,.08,'sine',.04,1.8);setTimeout(()=>tone(960,.12,'triangle',.035,1.1),60)}
function playHurt(){tone(190,.14,'sawtooth',.05,.55);tone(90,.18,'square',.024,.8)}
function playDash(){tone(260,.06,'triangle',.045,2.2);tone(900,.09,'sine',.03,1.4)}
function playPop(){tone(680,.05,'square',.032,1.5);tone(1160,.07,'triangle',.028,1.2)}
function shoot(){if(!running||player.fire>0)return;initAudio();const tx=mouse.active?mouse.x:W+120,ty=mouse.active?mouse.y:player.y,dist=Math.hypot(tx-player.x,ty-player.y)||1,dx=(tx-player.x)/dist,dy=(ty-player.y)/dist,color=pick(['#f9ff00','#00f5ff','#ff3df2','#8cff00','#ffffff']);darts.push({x:player.x+dx*34,y:player.y+dy*24,vx:dx*690+player.vx*.12,vy:dy*690+player.vy*.12,life:1.08,r:7,color,t:0,tail:[]});player.fire=.18;player.energy=clamp(player.energy-.45,0,100);playShoot();trail(player.x+dx*30,player.y+dy*20,color,8)}
function hit(a,b,rr){const dx=a.x-b.x,dy=a.y-b.y;return dx*dx+dy*dy<rr*rr}
function label(name){hitEl.textContent=name;clearTimeout(label.t);label.t=setTimeout(()=>{hitEl.textContent=running?'flying':'done'},900)}
function collect(o,d){streak++;bestStreak=Math.max(bestStreak,streak);score+=d.score+streak*2;player.energy=clamp(player.energy+(d.energy||0),0,100);if(d.time)timeLeft+=d.time;if(o.type==='bubble')player.inv=Math.max(player.inv,1.8);if(o.type==='feather')player.dash=Math.max(player.dash,.52);label(d.name);playCollect();burst(o.x,o.y,d.color,18)}
function hurt(o,d){player.energy-=d.damage;player.inv=1.05;player.slow=Math.max(player.slow,d.slow||0);player.vx-=160;player.vy+=rand(-120,120);streak=0;shake=.28;flash=.35;label(d.name);playHurt();burst(o.x,o.y,d.color,22)}
function update(dt){if(!running)return;timeLeft-=dt;if(timeLeft<=0||player.energy<=0){running=false;overlay.querySelector('.title').textContent='Dream Over';overlay.querySelector('.sub').textContent='Score '+score+' with a best streak of '+bestStreak+'. Hit more good objects and dodge the bad ones next run.';overlay.querySelector('.start').textContent='Restart';overlay.classList.remove('hidden');return}
let ax=0,ay=0;if(keys.has('ArrowLeft')||keys.has('a'))ax-=1;if(keys.has('ArrowRight')||keys.has('d'))ax+=1;if(keys.has('ArrowUp')||keys.has('w'))ay-=1;if(keys.has('ArrowDown')||keys.has('s'))ay+=1;if(mouse.active){const dx=mouse.x-player.x,dy=mouse.y-player.y,dist=Math.hypot(dx,dy);if(dist>8){ax=dx/dist;ay=dy/dist}}player.fire=Math.max(0,player.fire-dt);if(keys.has(' ')){if(player.dash<=0){player.dash=.38;player.vx+=(ax||1)*440;player.vy+=ay*330;player.energy=Math.max(0,player.energy-4);playDash()}keys.delete(' ')}if(keys.has('f')||keys.has('Enter')||mouse.active)shoot();
const slowMul=player.slow>0?.62:1,thrust=760*(player.dash>0?1.22:1)*slowMul;player.vx+=ax*thrust*dt;player.vy+=ay*thrust*dt;player.vy+=42*dt;player.vx*=Math.pow(.08,dt);player.vy*=Math.pow(.11,dt);player.x=clamp(player.x+player.vx*dt,42,W-42);player.y=clamp(player.y+player.vy*dt,68,H-44);player.dash=Math.max(0,player.dash-dt);player.inv=Math.max(0,player.inv-dt);player.slow=Math.max(0,player.slow-dt);player.energy=clamp(player.energy+dt*3.2,0,100);trail(player.x-30,player.y+rand(-10,10),player.dash>0?'#00f5ff':'#ff3df2',player.dash>0?3:1);
spawnT-=dt;ringT-=dt;hazardT-=dt;bonusT-=dt;if(spawnT<=0){spawnObject(pick(['candy','candy','star','feather']));spawnT=rand(.38,.72)}if(bonusT<=0){spawnObject(pick(['bubble','clock','star']));bonusT=rand(2.5,4.2)}if(ringT<=0){spawnRing();ringT=rand(2.1,3.2)}if(hazardT<=0){spawnObject(pick(['cloud','cloud','bolt','pillow']));hazardT=rand(1.05,1.75)}
for(const s of stars){s.x-=s.s*dt;if(s.x<-8){s.x=W+8;s.y=rand(0,H)}}
for(let i=darts.length-1;i>=0;i--){const d=darts[i];d.life-=dt;d.t+=dt;d.x+=d.vx*dt;d.y+=d.vy*dt;d.tail.push({x:d.x,y:d.y});if(d.tail.length>8)d.tail.shift();trail(d.x,d.y,d.color,1);if(d.life<=0||d.x>W+90||d.x<-90||d.y<-90||d.y>H+90)darts.splice(i,1)}
for(let i=objects.length-1;i>=0;i--){const o=objects[i],d=TYPES[o.type];o.x-=o.vx*dt;o.t+=dt;o.y+=Math.sin(o.t*2+o.bob)*10*dt;let dartHit=-1;for(let j=darts.length-1;j>=0;j--){if(hit(darts[j],o,darts[j].r+o.r)){dartHit=j;break}}if(dartHit>=0){const dart=darts[dartHit];burst(dart.x,dart.y,dart.color,12);if(d.kind==='good')collect(o,d);else{score+=12+streak;player.energy=clamp(player.energy+1.5,0,100);label('dart popped '+d.name);playPop();burst(o.x,o.y,d.color,26);shake=Math.max(shake,.1)}darts.splice(dartHit,1);objects.splice(i,1);continue}if(hit(player,o,player.r+o.r)){if(d.kind==='good')collect(o,d);else if(player.inv<=0)hurt(o,d);objects.splice(i,1);continue}if(o.x<-80)objects.splice(i,1)}
for(let i=rings.length-1;i>=0;i--){const r=rings[i];r.x-=185*dt;r.t+=dt;const d=Math.hypot(player.x-r.x,player.y-r.y);if(!r.hit&&d<r.r&&d>r.r-r.w-22){r.hit=true;streak++;bestStreak=Math.max(bestStreak,streak);score+=25*streak;player.energy=clamp(player.energy+8,0,100);label('lantern ring');playRing();burst(r.x,r.y,'#ffcf6f',24)}if(r.x<-90)rings.splice(i,1)}
for(let i=bursts.length-1;i>=0;i--){const p=bursts[i];p.life-=dt*1.7;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=90*dt;if(p.life<=0)bursts.splice(i,1)}shake=Math.max(0,shake-dt);flash=Math.max(0,flash-dt);updateHud()}
function drawSky(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'#090728');g.addColorStop(.45,'#111a5f');g.addColorStop(.72,'#31105c');g.addColorStop(1,'#07131b');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.save();ctx.globalCompositeOperation='lighter';let moon=ctx.createRadialGradient(W*.82,H*.18,0,W*.82,H*.18,140);moon.addColorStop(0,'rgba(249,255,0,.8)');moon.addColorStop(.28,'rgba(0,245,255,.25)');moon.addColorStop(1,'rgba(255,61,242,0)');ctx.fillStyle=moon;ctx.beginPath();ctx.arc(W*.82,H*.18,140,0,Math.PI*2);ctx.fill();for(let i=0;i<4;i++){ctx.strokeStyle=['#00f5ff','#ff3df2','#8cff00','#f9ff00'][i];ctx.globalAlpha=.16;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,H*(.22+i*.16));ctx.bezierCurveTo(W*.32,H*(.08+i*.18),W*.62,H*(.48-i*.08),W,H*(.2+i*.17));ctx.stroke()}ctx.restore();for(const s of stars){ctx.globalAlpha=s.a;ctx.fillStyle=s.r>1.3?'#00f5ff':'#fff7d1';ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;ctx.fillStyle='rgba(255,61,242,.08)';for(let i=0;i<7;i++){const y=H*.72+Math.sin(i+Date.now()/4000)*18;ctx.beginPath();ctx.ellipse((i*230-Date.now()/45)%(W+260)-120,y,130,24,0,0,Math.PI*2);ctx.fill()}}
function drawStarShape(x,y,r,color,spin=0){ctx.save();ctx.translate(x,y);ctx.rotate(spin);ctx.fillStyle=color;ctx.strokeStyle='rgba(255,255,255,.75)';ctx.lineWidth=2;ctx.beginPath();for(let i=0;i<10;i++){const a=i*Math.PI/5-Math.PI/2,rr=i%2?r*.45:r;ctx.lineTo(Math.cos(a)*rr,Math.sin(a)*rr)}ctx.closePath();ctx.fill();ctx.stroke();ctx.restore()}
function drawObject(o){const d=TYPES[o.type];ctx.save();ctx.translate(o.x,o.y);ctx.rotate(o.t*(o.type==='bolt'?.5:1.8));ctx.shadowColor=d.color;ctx.shadowBlur=16;if(o.type==='candy')drawStarShape(0,0,14,d.color,o.t*2);else if(o.type==='star')drawStarShape(0,0,18,d.color,o.t*2);else if(o.type==='bubble'){ctx.globalAlpha=.75;ctx.strokeStyle=d.color;ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,18,0,Math.PI*2);ctx.stroke();ctx.fillStyle='rgba(155,231,255,.16)';ctx.fill()}else if(o.type==='clock'){ctx.fillStyle='#c7ff7a';ctx.beginPath();ctx.arc(0,0,16,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#1f2b16';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(0,-9);ctx.moveTo(0,0);ctx.lineTo(8,3);ctx.stroke()}else if(o.type==='feather'){ctx.fillStyle=d.color;ctx.beginPath();ctx.ellipse(0,0,8,20,.65,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-7,14);ctx.lineTo(8,-15);ctx.stroke()}else if(o.type==='bolt'){ctx.fillStyle=d.color;ctx.beginPath();ctx.moveTo(-6,-22);ctx.lineTo(12,-4);ctx.lineTo(2,-3);ctx.lineTo(8,22);ctx.lineTo(-12,1);ctx.lineTo(-1,0);ctx.closePath();ctx.fill()}else if(o.type==='pillow'){ctx.fillStyle=d.color;ctx.beginPath();ctx.roundRect(-22,-14,44,28,9);ctx.fill();ctx.strokeStyle='rgba(85,65,140,.8)';ctx.stroke()}else if(o.type==='cloud'){ctx.globalAlpha=.92;ctx.fillStyle=d.color;for(const p of [[0,0,1],[-22,6,.72],[23,8,.82],[-4,-18,.76]]){ctx.beginPath();ctx.arc(p[0],p[1],34*p[2],0,Math.PI*2);ctx.fill()}ctx.fillStyle='rgba(65,50,96,.75)';ctx.beginPath();ctx.arc(-12,4,4,0,Math.PI*2);ctx.arc(12,4,4,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(65,50,96,.85)';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,15,10,Math.PI*.15,Math.PI*.85);ctx.stroke()}ctx.restore()}
function drawRing(r){ctx.save();ctx.translate(r.x,r.y);ctx.strokeStyle=r.hit?'#6ff0bd':'#ffcf6f';ctx.lineWidth=r.w;ctx.shadowColor=ctx.strokeStyle;ctx.shadowBlur=18;ctx.beginPath();ctx.arc(0,0,r.r,0,Math.PI*2);ctx.stroke();ctx.restore()}
function drawPanda(){ctx.save();ctx.translate(player.x,player.y);if(player.inv>0)ctx.globalAlpha=.45+.35*Math.sin(Date.now()/45);ctx.rotate(player.vx*.0009);const flap=Math.sin(Date.now()/120)*5;ctx.save();ctx.globalCompositeOperation='lighter';ctx.fillStyle=player.dash>0?'rgba(0,245,255,.38)':'rgba(255,61,242,.13)';ctx.beginPath();ctx.ellipse(-26,0,player.dash>0?62:42,player.dash>0?22:15,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(249,255,0,.35)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,38+Math.sin(Date.now()/120)*3,0,Math.PI*2);ctx.stroke();ctx.restore();ctx.fillStyle='rgba(0,0,0,.22)';ctx.beginPath();ctx.ellipse(0,34,36,9,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#f7f7f0';ctx.beginPath();ctx.arc(0,0,27,0,Math.PI*2);ctx.fill();ctx.fillStyle='#202026';ctx.beginPath();ctx.arc(-22,-19,11,0,Math.PI*2);ctx.arc(22,-19,11,0,Math.PI*2);ctx.fill();ctx.fillStyle='#202026';ctx.beginPath();ctx.ellipse(-10,-4,8,10,-.35,0,Math.PI*2);ctx.ellipse(10,-4,8,10,.35,0,Math.PI*2);ctx.fill();ctx.fillStyle='#f7f7f0';ctx.beginPath();ctx.arc(-10,-5,3,0,Math.PI*2);ctx.arc(10,-5,3,0,Math.PI*2);ctx.fill();ctx.fillStyle='#202026';ctx.beginPath();ctx.arc(0,8,5,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#202026';ctx.lineWidth=3;ctx.lineCap='round';ctx.beginPath();ctx.arc(0,14,10,.15*Math.PI,.85*Math.PI);ctx.stroke();ctx.strokeStyle='#202026';ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(-19,18);ctx.lineTo(-38,24+flap);ctx.moveTo(19,18);ctx.lineTo(38,24-flap);ctx.stroke();ctx.restore()}
function drawDarts(){ctx.save();ctx.globalCompositeOperation='lighter';for(const d of darts){ctx.strokeStyle=d.color;ctx.fillStyle=d.color;ctx.shadowColor=d.color;ctx.shadowBlur=22;ctx.lineWidth=3;ctx.globalAlpha=.78;if(d.tail.length){ctx.beginPath();ctx.moveTo(d.tail[0].x,d.tail[0].y);for(const p of d.tail)ctx.lineTo(p.x,p.y);ctx.lineTo(d.x,d.y);ctx.stroke()}ctx.globalAlpha=1;const a=Math.atan2(d.vy,d.vx);ctx.save();ctx.translate(d.x,d.y);ctx.rotate(a);ctx.beginPath();ctx.moveTo(15,0);ctx.lineTo(-8,-6);ctx.lineTo(-3,0);ctx.lineTo(-8,6);ctx.closePath();ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(-1,0,2.2,0,Math.PI*2);ctx.fill();ctx.restore()}ctx.restore();ctx.globalAlpha=1}
function drawBursts(){ctx.save();ctx.globalCompositeOperation='lighter';for(const p of bursts){ctx.globalAlpha=p.life;ctx.fillStyle=p.color;ctx.shadowColor=p.color;ctx.shadowBlur=14;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()}ctx.restore();ctx.globalAlpha=1}
function drawMouseTarget(){if(!mouse.active)return;ctx.save();ctx.globalCompositeOperation='lighter';ctx.strokeStyle='#00f5ff';ctx.fillStyle='rgba(0,245,255,.12)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(mouse.x,mouse.y,24+Math.sin(Date.now()/90)*4,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(mouse.x-34,mouse.y);ctx.lineTo(mouse.x+34,mouse.y);ctx.moveTo(mouse.x,mouse.y-34);ctx.lineTo(mouse.x,mouse.y+34);ctx.stroke();ctx.restore()}
function render(){ctx.save();if(shake>0)ctx.translate(rand(-6,6)*shake*4,rand(-4,4)*shake*4);drawSky();for(const r of rings)drawRing(r);for(const o of objects)drawObject(o);drawDarts();drawBursts();drawMouseTarget();drawPanda();if(flash>0){ctx.fillStyle='rgba(255,110,90,'+(flash*.32)+')';ctx.fillRect(0,0,W,H)}ctx.restore()}
function loop(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);render();requestAnimationFrame(loop)}
addEventListener('resize',resize);cv.addEventListener('pointerdown',e=>{initAudio();mouse.active=true;mouse.x=e.clientX;mouse.y=e.clientY;cv.setPointerCapture&&cv.setPointerCapture(e.pointerId)});cv.addEventListener('pointermove',e=>{mouse.x=e.clientX;mouse.y=e.clientY});cv.addEventListener('pointerup',e=>{mouse.active=false});cv.addEventListener('pointercancel',e=>{mouse.active=false});cv.addEventListener('dblclick',e=>{keys.add(' ')});addEventListener('keydown',e=>{initAudio();const k=e.key.length===1?e.key.toLowerCase():e.key;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','w','a','s','d','f','Enter'].includes(k)){e.preventDefault();keys.add(k)}});addEventListener('keyup',e=>{const k=e.key.length===1?e.key.toLowerCase():e.key;keys.delete(k)});
document.querySelectorAll('[data-k]').forEach(b=>{const k=b.dataset.k;b.addEventListener('pointerdown',e=>{e.preventDefault();if(k==='stop'){keys.clear();return}keys.add(k==='Space'?' ':k)});b.addEventListener('pointerup',()=>keys.delete(k==='Space'?' ':k));b.addEventListener('pointercancel',()=>keys.delete(k==='Space'?' ':k))});
document.getElementById('start').onclick=()=>{initAudio();reset()};resize();requestAnimationFrame(loop);
})();
